global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'soma@domain.com'
  smtp_auth_username: 'username'
  smtp_auth_password: 'password'

route:
  receiver: discord

receivers:
  - name: 'default-receiver'
    email_configs:
      - to: 'some@domain.com'
        send_resolved: true
  - name: discord
    discord_configs:
      - webhook_url: https://discord.com/api/webhooks/1333988487036276766/s8yC6c15rnSDatjjXP3HdmiGYOBAUpfH8pe6VRJAmDf0xQ4mRYqJTVj_BQxo_uz1mi8h