global:
  scrape_interval: 10s # How often to scrape targets by default.
  evaluation_interval: 10s # How often to evaluate rules.

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'python-metrics'
    static_configs:
      - targets: [ 'backend-server:5000' ]
